// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import fonts using className (not variable) to avoid hydration mismatch
const geistSans = Geist({
  subsets: ["latin"],
  display: "swap", // Makes font swap more graceful
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
});

// Metadata for the entire app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout applied to every page
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${geistMono.className} antialiased`}>
        {/* This wraps every page inside your app */}
        {children}
      </body>
    </html>
  );
}
