// Import type for setting page metadata (like title, description, etc.)
import type { Metadata } from "next";

// Import custom fonts from Google using Next.js font optimization
import { Geist, Geist_Mono } from "next/font/google";

// Import global styles
import "./globals.css";

// Import Providers component that will wrap the whole app (commonly used for SessionProvider, ThemeProvider, etc.)
import { Providers } from "./providers";

// Load Geist Sans font and assign it to a CSS variable
const geistSans = Geist({
  variable: "--font-geist-sans", // makes it available as a CSS custom property
  subsets: ["latin"], // optimize for Latin characters
});

// Load Geist Mono font and assign it to a CSS variable
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata for the entire application (used by Next.js for SEO and tab titles)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout wraps your entire app, including all pages and components
// `children` here represents the nested page content (like <Home />, <Dashboard />, etc.)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // children can be any valid React nodes/components
}>) {
  return (
    <html lang="en">
      <body
        // Apply both font variables and enable antialiasing for smoother font rendering
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*
          Wrap all page content (children) inside Providers.
          This allows things like SessionProvider, ThemeProvider, etc., 
          to make context available to every page. and they get
          automatically passed to there props
        */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
