# Defines a Persistent Volume resource in Kubernetes
apiVersion: v1
kind: PersistentVolume

# Metadata for the Persistent Volume
metadata:
  name: nfs-pv
  # Unique name of the PV within the cluster

# Specification for the Persistent Volume
spec:
  # Storage capacity of the volume
  capacity:
    storage: 5Gi
    # Specifies the size of the storage (5 gibibytes)

  # Access modes for the volume
  # ReadWriteMany allows multiple pods/nodes to read and write simultaneously
  accessModes:
    - ReadWriteMany
    # Suitable for NFS, which supports shared access

  # Reclaim policy: defines what happens when the bound PVC is deleted
  persistentVolumeReclaimPolicy: Retain
  # Retain keeps the PV and its data after PVC deletion for manual reuse
  # Alternatives: Delete (removes PV and data), Recycle (not recommended)

  # StorageClass for matching with PVCs or dynamic provisioning
  storageClassName: nfs-storage
  # Associates the PV with the 'nfs-storage' StorageClass
  # Used to match PVCs requesting this StorageClass
  # Optional for static PVs, but helps with organization and PVC binding

  # Specifies the NFS storage backend
  nfs:
    # Address of the NFS server (external to the cluster)
    server: 192.168.1.100
    # The IP or hostname of the NFS server hosting the storage
    # Path to the exported directory on the NFS server where data is stored
    path: /exports
    # The directory on the NFS server used for persistent storage


--------

# Defines a Persistent Volume resource in Kubernetes
apiVersion: v1
kind: PersistentVolume

# Metadata for the Persistent Volume
metadata:
  name: ebs-pv

# Specification for the Persistent Volume
spec:
  # Storage capacity
  capacity:
    storage: 10Gi

  # Access modes (EBS typically supports ReadWriteOnce)
  accessModes:
    - ReadWriteOnce

  # Reclaim policy
  persistentVolumeReclaimPolicy: Delete

  # Storage class for dynamic provisioning
  storageClassName: ebs-storage

  # Specifies the AWS EBS volume backend
  awsElasticBlockStore:
    # AWS EBS volume ID (created in AWS, external to the cluster)
    volumeID: vol-1234567890abcdef0
    # Filesystem type for the EBS volume
    fsType: ext4

-----------

# Defines a Persistent Volume Claim resource in Kubernetes
apiVersion: v1
kind: PersistentVolumeClaim

# Metadata for the PVC, including its name and namespace
metadata:
  name: example-pvc
  namespace: default

# Specification for the PVC
spec:
  # Access modes requested for the storage
  # Must match the access modes of the PV (e.g., ReadWriteOnce, ReadWriteMany)
  accessModes:
    - ReadWriteOnce

  # Requested storage capacity
  resources:
    requests:
      storage: 5Gi

  # Optional: Specifies a StorageClass for dynamic provisioning
  # If omitted, uses the default StorageClass or requires a manually created PV
  storageClassName: standard

  # Optional: Selector to match specific PVs (e.g., by labels)
  selector:
    matchLabels:
      app: my-storage
