import type { Metadata } from "next";
import "./globals.css"; // Ensure this includes all necessary styles
import { Inter } from "next/font/google"

//initalizing the font
const inter = Inter({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Dhruv App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> {/* adding fonts globally */}
        <div className="p-4 border-b-4 bg-slate-500">
          This is from layout.tsx
        </div>
        {children}
      </body>
    </html>
  );
}
