import type { Metadata } from "next";
import "./globals.css"; // Ensure this includes all necessary styles

export const metadata: Metadata = {
  title: "Create Dhruv App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased vsc-initialized"> {/* Keep it simple here */}
        <div className="p-4 border-b-4 bg-slate-500">
          This is from layout.tsx
        </div>
        {children}
      </body>
    </html>
  );
}
